import os
import time

# ANSI Farbcodes
GREEN = '\033[92m'
RED = '\033[91m'
YELLOW = '\033[93m'
CYAN = '\033[96m'
BOLD = '\033[1m'
RESET = '\033[0m'

# Start halt
def intro():
    print("\n" + "="*50)
    print(CYAN + BOLD + "🎮 HACKER TRAINING 🎮" + RESET)
    print("="*50)
    time.sleep(1)
    print("\n" + YELLOW + ">>> MISSION BRIEFING <<<" + RESET)
    time.sleep(2)
    print("\nHallo junger Agent! 🕵️")
    time.sleep(2)
    print("Willkommen in der EBGS Hacker Station")
    time.sleep(2)
    print("\nHeute lernst du, wie echte Hacker arbeiten.")
    time.sleep(2)
    print("Aber keine Sorge wir machen nichts Verbotenes! 😊")
    time.sleep(2)
    print("\n" + GREEN + "Bist du bereit für deine erste Mission?" + RESET)
    time.sleep(2)
    input("\nDrücke die ENTER Taste um zu starten...\n")
    
    print(YELLOW + "🚀 Mission wird geladen..." + RESET)
    time.sleep(2)


def challenge_2():
    print("\n" + "\n"*20)
    print(CYAN + "="*50)
    print("🎯 HACKER TRAINING - 6 MISSIONEN 🎯")
    print("="*50 + RESET)
    score = 0
    
    # Teil 1: Netzwerk Discovery
    print("\n" + "\n"*20)
    print(RED + "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓" + RESET)
    print(RED + "┃  🎯 MISSION 1: GEHEIME COMPUTER FINDEN  ┃" + RESET)
    print(RED + "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛" + RESET)
    time.sleep(2)
    print("\n📖 Deine Aufgabe:")
    time.sleep(2)
    print("Du Befindest dich Derzeit im Gebäude der EBGS und")
    time.sleep(3)
    print("Du willst wissen: Wie viele Computer sind hier?")
    time.sleep(2)
    print("\n💡 Hacker benutzen dafür einen Sogennanten SCANNER")
    time.sleep(2)
    print("Das ist wie ein Radar, das alle Computer findet und Aufspührt 📡")
    time.sleep(3)
    print("\n🔧 Dein Hacker Werkzeug Welches wir in der Console Eingeben ist:")
    time.sleep(1)
    print(RED + "nmap -sn 192.168.1.0/24" + RESET)
    time.sleep(2)
    print("\n(Das ist wie eine Schatzkarte um Alle Computer zur finden 🗺️)")
    time.sleep(2)
    input("\n⚡ Drücke ENTER auf der Tastatur vor dir um den Scanner zu starten...")
    
    print("\n" + GREEN + "🔄 Scanner wird gestartet..." + RESET)
    time.sleep(1)
    print(GREEN + "💻 Scanne Netzwerk..." + RESET)
    time.sleep(1)
    print(GREEN + "📡 Führe aus: nmap -sn 192.168.1.1-10" + RESET + "\n")
    os.system("nmap -sn 192.168.1.1-10")
    
    time.sleep(2)
    print("\n" + YELLOW + "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" + RESET)
    answer = input("\n❓ Schau nach oben Wie viele Computer hast du gefunden?\n   (Tipp: Schau bei der Zahl vor 'IP addresses'): ")
    print("\n" + GREEN + "🎉 SUPER! Du hast deinen ersten Scan gemacht" + RESET)
    print(YELLOW + "⭐ +10 Punkte für dich!" + RESET)
    score += 10
    time.sleep(3)
    
    # Teil 2: Port Scanning
    print("\n" + "\n"*20)
    print(RED + "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓" + RESET)
    print(RED + "┃   🚪 MISSION 2: OFFENE TÜREN FINDEN     ┃" + RESET)
    print(RED + "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛" + RESET)
    time.sleep(2)
    print("\n📖 Deine Aufgabe:")
    time.sleep(2)
    print("Jeder Computer ist wie ein Haus mit vielen Türen! 🏠")
    time.sleep(2)
    print("Manche Türen sind offen 🟢, manche sind zu 🔴")
    time.sleep(2)
    print("\n💡 Hacker schauen: Welche Türen sind offen?")
    time.sleep(2)
    print("So können sie in den Computer reinkommen!")
    time.sleep(3)
    print("\n🔧 Dein Hacker Werkzeug:")
    time.sleep(1)
    print(RED + "nmap -p 22,80,443 localhost" + RESET)
    time.sleep(2)
    input("\n⚡ Drücke ENTER um die Türen zu checken...")
    
    print("\n" + GREEN + "🔄 Tür Scanner wird gestartet..." + RESET)
    time.sleep(1)
    print(GREEN + "🚪 Schaue nach offenen Türen..." + RESET)
    time.sleep(1)
    print(GREEN + "📡 Führe aus: nmap -p 22,80,443 localhost" + RESET + "\n")
    os.system("nmap -p 22,80,443 localhost")
    
    time.sleep(2)
    print("\n" + YELLOW + "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" + RESET)
    print(CYAN + "\n👀 WICHTIG Schau genau hin!" + RESET)
    time.sleep(2)
    print("\nIn der Liste oben siehst du:")
    time.sleep(2)
    print("  🟢 " + GREEN + "open" + RESET + " = Tür ist offen")
    time.sleep(1)
    print("  🔴 " + RED + "closed" + RESET + " = Tür ist zu")
    time.sleep(2)
    print("\n🔍 Suche Tür Nummer 22!")
    time.sleep(2)
    print("(Das ist die SSH-Tür - damit können Hacker sich einloggen!)")
    time.sleep(2)
    
    answer = input("\n❓ Ist Tür 22 offen?\n   Schreib 'ja' wenn dort 'open' steht, sonst 'nein': ")
    if "ja" in answer.lower() or "nein" in answer.lower():
        print("\n" + GREEN + "🎯 RICHTIG! Du hast die Liste gelesen!" + RESET)
        time.sleep(2)
        if "ja" in answer.lower():
            print("Port 22 ist bei dir offen! 🟢")
        else:
            print("Port 22 ist bei dir geschlossen! 🔴")
        time.sleep(2)
        print(YELLOW + "⭐ +10 Punkte!" + RESET)
        print(GREEN + "Du wirst immer besser! 🌟" + RESET)
        score += 10
    else:
        print("\n" + YELLOW + "🤔 Schreib bitte 'ja' oder 'nein'..." + RESET)
        time.sleep(2)
        print("Aber keine Sorge!")
        time.sleep(1)
        print(GREEN + "⭐ +5 Punkte für's Mitmachen!" + RESET)
        score += 5
    time.sleep(3)
    
    # Teil 3: Service Detection
    print("\n" + "\n"*20)
    print(RED + "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓" + RESET)
    print(RED + "┃  🔍 MISSION 3: GEHEIME PROGRAMME FINDEN ┃" + RESET)
    print(RED + "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛" + RESET)
    time.sleep(2)
    print("\n📖 Deine Nächste Aufgabe:")
    time.sleep(2)
    print("Du hast offene Türen gefunden!")
    time.sleep(2)
    print("Jetzt willst du wissen: Was ist hinter den Türen sich Verbirgt? 🤔")
    time.sleep(2)
    print("\n💡 Läuft da eine Website? 🌐")
    time.sleep(2)
    print("Oder ein Login System für die PC's 🔐")
    time.sleep(2)
    print("Vielleicht sogar Passwörter? 🔑")
    time.sleep(3)
    print("\n🔧 Dein Hacker Werkzeug was wir nun in der Console Verwenden ist:")
    time.sleep(3)
    print(RED + "nmap -sV localhost" + RESET)
    time.sleep(2)
    input("\n⚡ Drücke ENTER um zu spionieren...")
    
    print("\n" + GREEN + "🔄 Spion Modus aktiviert..." + RESET)
    time.sleep(1)
    print(GREEN + "🕵️ Mal Schauen was der Computer macht..." + RESET)
    time.sleep(1)
    print(GREEN + "📡 Führe aus: nmap -sV -p 22,80,443 localhost" + RESET + "\n")
    os.system("nmap -sV -p 22,80,443 localhost")
    
    time.sleep(2)
    print("\n" + GREEN + "🎉 Wow! Du gehst nun wie ein Echter hacker vor" + RESET)
    print(YELLOW + "⭐ +10 Punkte!" + RESET)
    score += 10
    time.sleep(3)
    
    # Teil 4: OS Detection
    print("\n" + "\n"*20)
    print(RED + "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓" + RESET)
    print(RED + "┃  💻 MISSION 4: COMPUTER-GEHIRN SCANNEN  ┃" + RESET)
    print(RED + "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛" + RESET)
    time.sleep(2)
    print("\n" + YELLOW + "🎊 Hey! Du bist schon super weit gekommen!" + RESET)
    time.sleep(2)
    print("\n📖 Deine Nächste Aufgabe:")
    time.sleep(2)
    print("Jeder Computer hat ein 'Gehirn' auch Betriebssystem Gennant 🧠")
    time.sleep(2)
    print("Das ist wie ein Chef, der alles steuert und Kontrolliert")
    time.sleep(2)
    print("\nEs gibt:")
    time.sleep(1)
    print("  • Windows 🪟 (kennst du bestimmt!) welches wir auch für Die Schul PC's Verwenden")
    time.sleep(1)
    print("  • Mac 🍎 (von Apple)")
    time.sleep(1)
    print("  • Linux 🐧 (das benutzen viele Hacker & Herr Van DE LOO")
    time.sleep(3)
    print("\n💡 Warum ist das wichtig?")
    time.sleep(2)
    print("Jedes System funktioniert anders")
    time.sleep(2)
    print("Hacker müssen das wissen um sich Anzupassen 🎯")
    time.sleep(3)
    print("\n🔧 Dein Hacker Werkzeug für diese Aufgabe:")
    time.sleep(1)
    print(RED + "uname -a" + RESET)
    time.sleep(2)
    input("\n⚡ Drücke ENTER um das Betriebsystem zu scannen...")
    
    print("\n" + GREEN + "🔄 Betriebsystem Scanner wird gestartet..." + RESET)
    time.sleep(1)
    print(GREEN + "🧠 Analysiere Betriebssystem..." + RESET)
    time.sleep(1)
    print(GREEN + "📡 Führe aus: uname -a" + RESET + "\n")
    time.sleep(1)
    os.system("uname -a")
    
    time.sleep(2)
    print("\n" + YELLOW + "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" + RESET)
    answer = input("\n❓ Steht im Langen Text 'Linux' oder 'Kali'?\n   Schreib 'ja' oder 'nein': ")
    if "ja" in answer.lower():
        print("\n" + GREEN + "🎯 PERFEKT! Du liest wie ein Profi!" + RESET)
        print(YELLOW + "⭐ +10 Punkte!" + RESET)
        score += 10
    else:
        print("\n" + YELLOW + "🔍 Schau nochmal genau hin!" + RESET)
        print("Das Wort 'Linux' versteckt sich da Vielleicht doch irgendwo! 👀")
    time.sleep(3)
    
    # Teil 5: Netzwerk Analyse
    print("\n" + "\n"*20)
    print(RED + "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓" + RESET)
    print(RED + "┃  🏠 MISSION 5: COMPUTER ADRESSE FINDEN  ┃" + RESET)
    print(RED + "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛" + RESET)
    time.sleep(2)
    print("\n📖 Deine Aufgabe:")
    time.sleep(2)
    print("Jeder Computer hat eine Adresse! 📮")
    time.sleep(2)
    print("Wie dein Haus eine Hausnummer hat (z.B. Industriestraße 29)")
    time.sleep(2)
    print("\n💡 Computer Adressen sehen aber nicht aus wie eine Normale Hausnummer sondern Sehen so aus:")
    time.sleep(5)
    print(CYAN + "192.168.1.10" + RESET + " oder " + CYAN + "10.0.0.5" + RESET)
    time.sleep(2)
    print("\nHacker brauchen diese Adressen")
    time.sleep(2)
    print("Sonst finden sie den Computer nicht den sie Hacken wollen")
    time.sleep(3)
    print("\n🔧 Dein Hacker Werkzeug das wir diesmal nutzen ist:")
    time.sleep(1)
    print(RED + "ip addr" + RESET)
    time.sleep(2)
    input("\n⚡ Drücke ENTER um die Adresse zu finden...")
    
    print("\n" + GREEN + "🔄 Adressen Sucher wird gestartet..." + RESET)
    time.sleep(1)
    print(GREEN + "🏠 Suche Computer Adresse..." + RESET)
    time.sleep(1)
    print(GREEN + "📡 Führe aus: ip addr show" + RESET + "\n")
    os.system("ip addr show | grep inet || ifconfig")
    
    time.sleep(2)
    print("\n" + GREEN + "🎉 Gefunden! Das sind die Adressen!" + RESET)
    print(YELLOW + "⭐ +10 Punkte!" + RESET)
    score += 10
    time.sleep(3)
    
    # Bonus Challenge
    print("\n" + "\n"*20)
    print(RED + "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓" + RESET)
    print(RED + "┃    📶 BONUS MISSION: WLAN HACKER       ┃" + RESET)
    print(RED + "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛" + RESET)
    time.sleep(2)
    print("\n" + YELLOW + "🌟 BONUS MISSION FREIGESCHALTET!" + RESET)
    time.sleep(2)
    print("\n📖 Letzte Aufgabe:")
    time.sleep(2)
    print("Finde alle WLAN Netzwerke in der Nähe! 📡")
    time.sleep(2)
    print("Das ist wie auf deinem Handy wenn du nach WLAN suchst! 📱")
    time.sleep(2)
    print("\n💡 Aber als Hacker siehst du VIEL mehr Infos!")
    time.sleep(2)
    print("Zum Beispiel:")
    time.sleep(1)
    print("  • Wie stark ist das Signal? 📶")
    time.sleep(1)
    print("  • Welcher Kanal wird benutzt? 📻")
    time.sleep(1)
    print("  • Ist das WLAN verschlüsselt? 🔒")
    time.sleep(1)
    print("  • Welche Sicherheit wird verwendet? 🛡️")
    time.sleep(1)
    print("  • Die genaue WLAN Adresse wo sich das Befindet (MAC Adresse)! 📍")
    time.sleep(3)
    print("\n🔧 Dein Hacker Werkzeug für die Letzte Station ist:")
    time.sleep(1)
    print(RED + "nmcli dev wifi" + RESET)
    time.sleep(2)
    input("\n⚡ Drücke ENTER für den WLAN Scan mit nmcli dev wifi Auszuführen...")
    
    print("\n" + GREEN + "🔄 WLAN Scanner wird gestartet..." + RESET)
    time.sleep(1)
    print(GREEN + "📶 Suche nach WLAN Netzwerken..." + RESET)
    time.sleep(1)
    print(GREEN + "📡 Führe aus: nmcli dev wifi" + RESET + "\n")
    os.system("nmcli dev wifi || iwconfig")
    
    time.sleep(2)
    answer = input("\n❓ Siehst du WLAN Namen in der Liste?\n   Schreib 'ja' oder 'nein': ")
    if "ja" in answer.lower():
        print("\n" + GREEN + "🏆 UNGLAUBLICH! Du bist ein Profi" + RESET)
        print(YELLOW + "⭐⭐ +20 BONUS PUNKTE! ⭐⭐" + RESET)
        score += 20
    else:
        print("\n" + YELLOW + "Kein Problem! Du Hast Trotzdem gut Abgeschnitten wie man auch Gleich in der Punkte Anzahl sieht" + RESET)
    time.sleep(6)
    
    # ende
    print("\n" + "\n"*20)
    print(CYAN + "="*50)
    print("🎊 MISSION ABGESCHLOSSEN 🎊")
    print("="*50 + RESET)
    time.sleep(2)
    print("\n" + YELLOW + "📊 DEINE PUNKTE: " + str(score) + " von 70 Punkten" + RESET)
    time.sleep(2)
    
    if score >= 60:
        print("\n" + GREEN + "🏆🏆🏆 ELITE-HACKER! 🏆🏆🏆" + RESET)
        print("Du bist ein Echter profi")
    elif score >= 40:
        print("\n" + GREEN + "⭐⭐ SUPER HACKER! ⭐⭐" + RESET)
        print("Du hast echt Talent!")
    elif score >= 20:
        print("\n" + GREEN + "⭐ JUNIOR HACKER! ⭐" + RESET)
        print("Guter Start!")
    else:
        print("\n" + GREEN + "🎮 HACKER 🎮" + RESET)
        print("Weiter so!")
    
    time.sleep(2)
    print("\n" + CYAN + "="*50 + RESET)
    
    # Zusammenfassung
    print("\n" + YELLOW + "📚 WAS DU HEUTE GELERNT HAST:" + RESET)
    time.sleep(1)
    print("\n  1. 📡 Computer im Netzwerk finden")
    time.sleep(1)
    print("  2. 🚪 Offene Türen (Ports) scannen")
    time.sleep(1)
    print("  3. 🕵️ Programme hinter den Türen des Netzwerkes finden")
    time.sleep(1)
    print("  4. 💻 Betriebssystem erkennen")
    time.sleep(1)
    print("  5. 🏠 Computer Adressen finden")
    time.sleep(1)
    print("  6. 📶 WLAN Netzwerke scannen")
    time.sleep(2)
    
    print("\n" + RED + "⚠️ WICHTIGE HACKER REGEL:" + RESET)
    time.sleep(1)
    print("Nur mit Erlaubnis hacken")
    time.sleep(1)
    print("Sonst ist es VERBOTEN und du bekommst du sehr großen Ärger und das wollen wir ja nicht 👮")
    time.sleep(2)
    return score

def main():
    intro()
    challenge_2()
    
    print("\n" + "\n"*5)
    print(CYAN + "="*50)
    print("👋 MISSION ENDE 👋")
    print("="*50 + RESET)
    time.sleep(2)
    print("\n" + GREEN + "Danke fürs Mitmachen!" + RESET)
    time.sleep(1)
    print("wir von der EBGS Wünschen dir noch viel Spaß bei den Nächsten Stationen! 🎮")
    time.sleep(2)
    print("\n" + YELLOW + "🌟 Bis zum nächsten Mal 🌟" + RESET)
    print("\n" + "="*50 + "\n")
    time.sleep(2)

if __name__ == "__main__":
    main()
